[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "heraldo"
version = "0.1.0"
description = "Photonic circuit optimization and quantum state engineering framework."
authors = [
    { name = "Sadeq Ismailzadeh" }
]
license = { text = "MIT" }
requires-python = "==3.13.*"
dependencies = [
    "strawberryfields",
    "numpy",
    "scipy",
    "numba",
    "thewalrus",
    "sympy",
    "pandas",
    "tqdm",
    "matplotlib",
    "setuptools<75",
    "pip",
]

[dependency-groups]
docs = [
    "sphinx>=7.0.0",
    "myst-parser>=2.0.0",
    "sphinx-rtd-theme>=1.3.0",
    "docutils<0.21",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["heraldo*"]