"""Target state generators implementing the TargetGenerator interface."""


# 1. Import the module we need to patch
import scipy.integrate

# 2. Check if the patch is needed to avoid errors
if not hasattr(scipy.integrate, 'simps'):
    print("Monkey patching scipy.integrate: 'simps' not found. Pointing to 'simpson'.")
    # 3. Create the 'simps' attribute and point it to the existing 'simpson' function.
    scipy.integrate.simps = scipy.integrate.simpson
else:
    print("'simps' already exists in scipy.integrate. No patch needed.")

import abc
import numpy as np
import strawberryfields as sf
from strawberryfields.ops import Sgate, Dgate, Vgate, Catstate, Ket
from scipy.special import factorial, comb
import pandas as pd

class TargetGenerator(abc.ABC):
    """Abstract base class for target state generators in the Fock basis.

    Subclasses implement specific non-Gaussian or Gaussian quantum state
    preparations used as targets in circuit optimization.
    """

    @abc.abstractmethod
    def get_target_ket(self, cutoff_dim: int) -> np.ndarray:
        """Generates the target state vector (ket) in the Fock basis.

        Args:
            cutoff_dim (int): The Fock space truncation cutoff dimension.

        Returns:
            np.ndarray: Complex 1D array representing the state vector in Fock space.
        """
        pass


# --- Target Implementations ---


class SqueezedCatTarget(TargetGenerator):
    """Generates squeezed Schrödinger cat state targets.

    The state is generated by applying a squeezing operator to a coherent cat state:
    :math:`\\hat{S}(r) \\mathcal{N}_p (|\\alpha\\rangle + (-1)^p |-\\alpha\\rangle)`.

    Args:
        alpha (float, optional): Coherent state amplitude :math:`\\alpha`. Defaults to 3.0.
        r (float, optional): Squeezing parameter :math:`r`. Defaults to 1.38.
        p (int, optional): Parity indicator (0 for even cat, 1 for odd cat). Defaults to 0.
    """

    def __init__(self, alpha=3.0, r=1.38, p=0):
        self.alpha = alpha
        self.r = r
        self.p = p

    def get_target_ket(self, cutoff_dim: int) -> np.ndarray:
        """Generates the squeezed cat target state vector.

        Args:
            cutoff_dim (int): The Fock space cutoff dimension.

        Returns:
            np.ndarray: The target state ket in the Fock basis.
        """
        print(f"Generating Squeezed Cat Target (alpha={self.alpha}, r={self.r}, p={self.p})...")

        prog = sf.Program(1)
        with prog.context as q:
            Catstate(a=self.alpha, p=self.p) | q[0]
            Sgate(r=self.r) | q[0]

        eng = sf.Engine("fock", backend_options={"cutoff_dim": cutoff_dim})
        state = eng.run(prog).state

        return state.ket()


class CatTarget(TargetGenerator):
    """Generates unsqueezed Schrödinger cat state targets.

    The state is defined as:
    :math:`\\mathcal{N}_p (|\\alpha\\rangle + (-1)^p |-\\alpha\\rangle)`.

    Args:
        alpha (float, optional): Coherent state amplitude :math:`\\alpha`. Defaults to 3.0.
        p (int, optional): Parity indicator (0 for even cat, 1 for odd cat). Defaults to 0.
    """

    def __init__(self, alpha=3.0, p=0):
        self.alpha = alpha
        self.p = p

    def get_target_ket(self, cutoff_dim: int) -> np.ndarray:
        """Generates the cat state target vector.

        Args:
            cutoff_dim (int): The Fock space cutoff dimension.

        Returns:
            np.ndarray: The target state ket in the Fock basis.
        """
        print(f"Generating Cat Target (alpha={self.alpha}, p={self.p})...")

        prog = sf.Program(1)
        with prog.context as q:
            Catstate(a=self.alpha, p=self.p) | q[0]

        eng = sf.Engine("fock", backend_options={"cutoff_dim": cutoff_dim})
        state = eng.run(prog).state

        return state.ket()


class CubicPhaseTarget(TargetGenerator):
    """Generates cubic phase target states.

    The target state is defined as:
    :math:`|\\gamma, r, \\alpha\\rangle = \\hat{D}(\\alpha) \\exp(i \\gamma \\hat{q}^3) \\hat{S}(r) |0\\rangle`.

    Args:
        gamma (float, optional): Cubic phase nonlinearity parameter :math:`\\gamma`. Defaults to -0.2.
        r (float, optional): Squeezing parameter :math:`r`. Defaults to -0.7.
        alpha (float, optional): Displacement amplitude :math:`\\alpha` (applied along the imaginary axis). Defaults to 1.25.
    """

    def __init__(self, gamma=-0.2, r=-0.7, alpha=1.25):
        self.gamma = gamma
        self.r = r
        self.alpha = alpha

    def get_target_ket(self, cutoff_dim: int) -> np.ndarray:
        """Generates the cubic phase target state vector.

        Args:
            cutoff_dim (int): The Fock space cutoff dimension.

        Returns:
            np.ndarray: The target state ket in the Fock basis.
        """
        print(f"Generating Target Cubic Phase State (gamma={self.gamma}, r={self.r}, alpha={self.alpha})...")

        prog = sf.Program(1)
        with prog.context as q:
            # Order: vacuum -> squeezing -> cubic phase -> displacement
            Sgate(self.r) | q[0]

            # Cubic Phase: exp(i * gamma * Q^3)
            Vgate(self.gamma * 2) | q[0]

            # Displacement (typically imaginary)
            z = 1j * self.alpha
            r = np.abs(z)
            theta = np.angle(z)
            Dgate(r, theta) | q[0]

        eng = sf.Engine("fock", backend_options={"cutoff_dim": cutoff_dim})
        state = eng.run(prog).state

        return state.ket()


class CubicResourceTarget(TargetGenerator):
    """Generates cubic phase resource state targets for gadget circuits.

    Constructed as a finite superposition in the Fock basis:
    :math:`|\\psi\\rangle \\propto |0\\rangle + i a \\sqrt{1.5} |1\\rangle + i a |3\\rangle`.

    Args:
        a (float, optional): Normalization scaling coefficient. Defaults to 0.61.
    """

    def __init__(self, a=0.61):
        self.a = a

    def get_target_ket(self, cutoff_dim: int) -> np.ndarray:
        """Generates the cubic resource target state vector.

        Args:
            cutoff_dim (int): The Fock space cutoff dimension.

        Returns:
            np.ndarray: The normalized target state ket in the Fock basis.
        """
        print("Initializing Cubic Phase Target State for Gadget...")
        base_ket = np.zeros(cutoff_dim, dtype=np.complex128)
        base_ket[0] = 1.0
        base_ket[1] = 1j * self.a * np.sqrt(1.5)
        base_ket[3] = 1j * self.a
        base_ket /= np.linalg.norm(base_ket)
        return base_ket


class CoreGKPTarget(TargetGenerator):
    """Generates approximate Gottesman-Kitaev-Preskill (GKP) core target states.

    Uses the stellar representation (core state + squeezing) derived from tabulated
    coefficients in a CSV file.

    Args:
        csv_path (str, optional): Path to the CSV file containing GKP coefficients.
            Defaults to 'GKP_core_coefficients.csv'.
        n_max (int, optional): Maximum stellar rank / Fock cutoff (e.g., 2, 4, 6, 8, 10, 12).
            Defaults to 4.
        delta_db (float, optional): Target envelope parameter :math:`\\Delta` in dB (e.g., 10.0).
            Defaults to 10.0.
        mu (int, optional): Logical state index (0 or 1). Defaults to 0.
        apply_squeezing (bool, optional): Whether to apply the squeezing transformation
            to the core state. Defaults to False.
    """

    def __init__(self, csv_path='GKP_core_coefficients.csv', n_max=4, delta_db=10.0, mu=0, apply_squeezing=False):
        self.csv_path = csv_path
        self.n_max = n_max
        self.delta_db = delta_db
        self.mu = mu
        self.apply_squeezing = apply_squeezing

    def get_target_ket(self, cutoff_dim: int) -> np.ndarray:
        """Loads GKP coefficients from CSV and applies squeezing if configured.

        Args:
            cutoff_dim (int): The Fock space cutoff dimension.

        Returns:
            np.ndarray: The target GKP core state ket in the Fock basis.

        Raises:
            FileNotFoundError: If the CSV file at `csv_path` does not exist.
        """
        verbose = 0
        if (verbose > 0):
            print(f"Generating Core GKP Target (|{self.mu}>_A, n_max={self.n_max}, Delta={self.delta_db}dB)...")

        # 1. Load CSV data
        try:
            df = pd.read_csv(self.csv_path)
        except FileNotFoundError:
            raise FileNotFoundError(f"GKP coefficients file not found at {self.csv_path}. Please ensure the CSV is present.")

        # 2. Find matching row
        row = df[(df['n_max'] == self.n_max) & (np.abs(df['Delta (dB)'] - self.delta_db) < 1e-5)]

        if row.empty:
            closest_idx = (df[df['n_max'] == self.n_max]['Delta (dB)'] - self.delta_db).abs().idxmin()
            row = df.loc[[closest_idx]]
            print(f"Warning: Exact Delta={self.delta_db}dB not found for n_max={self.n_max}. Using closest match: {row['Delta (dB)'].values[0]}dB")

        # 3. Extract squeezing (r) and core coefficients (c)
        sfx = str(self.mu)
        r_db = row[f'r{sfx} (dB)'].values[0]
        r_param = (np.log(10) / 20.0) * r_db

        base_ket = np.zeros(cutoff_dim, dtype=np.complex128)
        for n in range(0, self.n_max + 1, 2):
            col_name = f'c{sfx}_{n}'
            if col_name in row.columns:
                base_ket[n] = row[col_name].values[0]

        base_ket /= np.linalg.norm(base_ket)

        if (verbose > 0):
            print(f"Core state (stellar representation) for n_max={self.n_max}:")
            for n, val in enumerate(base_ket):
                if np.abs(val) > 1e-6:
                    out_val = val.real if np.abs(val.imag) < 1e-8 else val
                    print(f"  |{n}>: {out_val:.6f}")

        # 4. Use Strawberry Fields to apply Squeezing to the core ket
        prog = sf.Program(1)
        with prog.context as q:
            Ket(base_ket) | q[0]
            if self.apply_squeezing:
                Sgate(r_param) | q[0]

        eng = sf.Engine("fock", backend_options={"cutoff_dim": cutoff_dim})
        state = eng.run(prog).state

        return state.ket()


class BinomialCodeTarget(TargetGenerator):
    """Generates binomial quantum error-correcting code target states.

    The logical codewords are defined as:
    :math:`|W_\\mu\\rangle = \\frac{1}{\\sqrt{2^N}} \\sum_{p} \\sqrt{\\binom{N+1}{p}} |p(S+1)\\rangle`,
    where :math:`p` sums over even integers for logical 0 (:math:`\\mu=0`) and odd integers for logical 1 (:math:`\\mu=1`).

    Args:
        N (int, optional): Order parameter of the binomial code. Defaults to 1.
        S (int, optional): Spacing parameter of the binomial code. Defaults to 1.
        mu (int, optional): Logical state index (0 or 1). Defaults to 0.
    """

    def __init__(self, N=1, S=1, mu=0):
        self.N = N
        self.S = S
        self.mu = mu

    def get_target_ket(self, cutoff_dim: int) -> np.ndarray:
        """Generates the binomial code target state vector.

        Args:
            cutoff_dim (int): The Fock space cutoff dimension.

        Returns:
            np.ndarray: The target state ket in the Fock basis.
        """
        print(f"Generating Binomial Code Target (N={self.N}, S={self.S}, mu={self.mu})...")

        target_ket = np.zeros(cutoff_dim, dtype=np.complex128)

        start_p = 1 if self.mu == 1 else 0

        for p in range(start_p, self.N + 2, 2):
            fock_n = p * (self.S + 1)

            if fock_n < cutoff_dim:
                c = np.sqrt(comb(self.N + 1, p))
                target_ket[fock_n] = c

        norm = np.linalg.norm(target_ket)
        if norm > 1e-9:
            target_ket /= norm

        return target_ket
